# Docker Compose
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: timesheet_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/timesheet_db
    ports:
      - '8000:8000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timesheet_frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  pgdata:
